Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$projectRoot = Split-Path -Parent $PSScriptRoot
$publishScript = Join-Path $PSScriptRoot "publish.ps1"
$signScript = Join-Path $PSScriptRoot "sign-local-build.ps1"
$iconScript = Join-Path $PSScriptRoot "ensure-app-icon.ps1"
$issPath = Join-Path $projectRoot "installer\kikisenapp.iss"
$installerDir = Join-Path $projectRoot "installer"
$downloadCacheDir = Join-Path $installerDir "downloads"
$generatedIncludePath = Join-Path $installerDir "download-files.generated.iss"
$distDir = Join-Path $projectRoot "dist"
$vbCablePageUrl = "https://vb-audio.com/Cable/"

if (-not (Test-Path $issPath)) {
    throw "Inno Setup script was not found: $issPath"
}

function Get-VbCablePackageInfo {
    $response = Invoke-WebRequest -Uri $vbCablePageUrl -UseBasicParsing
    $match = [System.Text.RegularExpressions.Regex]::Match(
        $response.Content,
        'https://download\.vb-audio\.com/Download_CABLE/VBCABLE_Driver_Pack\d+\.zip',
        [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)

    if (-not $match.Success) {
        throw "VB-CABLE download URL was not found on the official page."
    }

    $downloadUrl = $match.Value
    [pscustomobject]@{
        DownloadUrl = $downloadUrl
        FileName = [System.IO.Path]::GetFileName(([uri]$downloadUrl).AbsolutePath)
    }
}

function Save-FileIfNeeded {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Url,

        [Parameter(Mandatory = $true)]
        [string]$DestinationPath
    )

    if (Test-Path $DestinationPath) {
        $existingFile = Get-Item $DestinationPath
        if ($existingFile.Length -gt 0) {
            return
        }
    }

    Invoke-WebRequest -Uri $Url -OutFile $DestinationPath -UseBasicParsing
}

function Expand-VbCableArchive {
    param(
        [Parameter(Mandatory = $true)]
        [string]$ArchivePath,

        [Parameter(Mandatory = $true)]
        [string]$DestinationPath
    )

    $expectedFile = Join-Path $DestinationPath "VBCABLE_Setup_x64.exe"
    if (Test-Path $expectedFile) {
        return
    }

    if (Test-Path $DestinationPath) {
        Remove-Item -Path $DestinationPath -Recurse -Force
    }

    New-Item -ItemType Directory -Force $DestinationPath | Out-Null
    Expand-Archive -Path $ArchivePath -DestinationPath $DestinationPath -Force
}

function Write-GeneratedInstallerInclude {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,

        [Parameter(Mandatory = $true)]
        [string]$VbCableExtractPath
    )

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add('; This file is generated by scripts/build-installer.ps1')
    $lines.Add('Source: "' + $VbCableExtractPath + '\*"; DestDir: "{tmp}\VBCABLE"; Flags: ignoreversion recursesubdirs createallsubdirs; Tasks: vbcable')

    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllLines($Path, $lines, $utf8NoBom)
}

New-Item -ItemType Directory -Force $downloadCacheDir | Out-Null

& powershell -ExecutionPolicy Bypass -File $iconScript

$vbCablePackage = Get-VbCablePackageInfo
$vbCableArchivePath = Join-Path $downloadCacheDir $vbCablePackage.FileName
$vbCableExtractPath = Join-Path $downloadCacheDir "VBCABLE"

Save-FileIfNeeded -Url $vbCablePackage.DownloadUrl -DestinationPath $vbCableArchivePath
Expand-VbCableArchive -ArchivePath $vbCableArchivePath -DestinationPath $vbCableExtractPath
Write-GeneratedInstallerInclude -Path $generatedIncludePath -VbCableExtractPath $vbCableExtractPath

& powershell -ExecutionPolicy Bypass -File $publishScript

$isccCandidates = @(
    "C:\Program Files (x86)\Inno Setup 6\ISCC.exe",
    "C:\Program Files\Inno Setup 6\ISCC.exe",
    "$env:LOCALAPPDATA\Programs\Inno Setup 6\ISCC.exe"
)

$isccPath = $isccCandidates | Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $isccPath) {
    $innoInstall = Get-ItemProperty `
        "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*" `
        ,"HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*" `
        ,"HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*" `
        -ErrorAction SilentlyContinue |
        Where-Object { $_.DisplayName -like "Inno Setup*" } |
        Select-Object -First 1

    if ($innoInstall -and $innoInstall.InstallLocation) {
        $candidate = Join-Path $innoInstall.InstallLocation "ISCC.exe"
        if (Test-Path $candidate) {
            $isccPath = $candidate
        }
    }
}

if (-not $isccPath) {
    throw "ISCC.exe was not found. Inno Setup 6 is required."
}

New-Item -ItemType Directory -Force $distDir | Out-Null

& $isccPath $issPath

$setupExe = Join-Path $distDir "KikisenApp-Setup.exe"
if (-not (Test-Path $setupExe)) {
    throw "setup.exe was not created."
}

& powershell -ExecutionPolicy Bypass -File $signScript -FilePaths $setupExe
